default:
  # Basic runtime config
  dt_cores:             64 # Number of cores that data.table is going to use
  dt_verbose:           FALSE # Should data.table be verbose
  mcl_bin:              "mcl" # Where is the MCL binary
  mcl_inflation_min:    1.2 # Minimum MCL inflation value
  mcl_inflation_max:    3.0 # Maximum MCL inflation value
  mcl_inflation_step:   0.1 # MCL inflation step
  mcl_jobs:             2 # How many simultaneous MCL jobs should be ran
  mcl_cores:            32 # How many cores MCL will use
  max_gc_jobs:          19 # How many simulatneous jobs are going to be used for the inflation values
  entropy_cores:        32 # Number of cores to calculate MCL cluster entropy (uses a lot of RAM, 32 for bigmems)
  das_refinement_cores: 64
  # Files
  wd:                   "/vol/cloud/db_creation/cluster_communities"
  graph_lib:            "/vol/cloud/agnostos-wf/db_creation/scripts/communities_inference/graph_lib.R"
  cl_cat:               "/vol/cloud/db_creation/cluster_categories/cluster_ids_categ.tsv"
  cl_comp:              "/vol/cloud/db_creation/cluster_category_stats/cluster_category_completeness.tsv"
  p_clan:               "/vol/cloud/agnostos-wf/databases/Pfam-A.clans.tsv.gz"
  p_doms:               "/vol/cloud/db_creation/cluster_classification/cluster_pfam_domain_architectures.tsv"
  hhblits_db_creation:      "/vol/cloud/db_creation/cluster_communities/k_hhblits.tsv"
  # Files with db_creation that can be loaded to skip time consuming steps, leave it empty to recalculate them
  k_g_mcl_list:         ""
  k_gc:                 ""
  k_gc_da_sg:           ""
  k_gc_entropy:         ""
  da_dist:              ""
  k_das_refinement:     ""

  kwp_hhblits_db_creation:  "/vol/cloud/db_creation/cluster_communities/kwp_hhblits.tsv"
  kwp_g_mcl_list:       ""
  kwp_gc:               ""
  gu_hhblits_db_creation:   "/vol/cloud/db_creation/cluster_communities/gu_hhblits.tsv"
  gu_g_mcl_list:        ""
  gu_gc:                ""
  eu_hhblits_db_creation:   "/vol/cloud/db_creation/cluster_communities/eu_hhblits.tsv"
  eu_g_mcl_list:        ""
  eu_gc:                ""
