__default__:
    time: 1000:00:00
    ntasks: 1
    nodes: 1
    ntasks_per_node: 1
    partition: nomaster
    cpus_per_task: 1

pfam_annotation:
    nodes: 5
    ntasks: 10
    ntasks_per_node: 2
    cpus_per_task: 14
    partition: nomaster

spurious_shadow:
    nodes: 7
    ntasks: 196
    ntasks_per_node: 28
    cpus_per_task: 1
    partition: nomaster

mmseqs_clustering:
    nodes: 7
    ntasks: 7
    ntasks_per_node: 1
    cpus_per_task: 28
    partition: nomaster

mmseqs_clustering_results:
    nodes: 7
    ntasks: 14
    ntasks_per_node: 2
    cpus_per_task: 14
    partition: nomaster

mmseqs_clustering_update:
    nodes: 7
    ntasks: 7
    ntasks_per_node: 1
    cpus_per_task: 28
    partition: nomaster

mmseqs_clustering_updt_results:
    nodes: 7
    ntasks: 14
    ntasks_per_node: 2
    cpus_per_task: 14
    partition: nomaster

cluster_compositional_validation:
    nodes: 7
    ntasks: 28
    ntasks_per_node: 4
    partition: nomaster

cluster_refinement:
    nodes: 7
    ntasks: 7
    ntasks-per_node: 1
    cpus_per_task: 28
    partition: nomaster

cluster_classification:
    time: 1000:00:00
    nodes: 7
    ntasks_per_node: 1
    ntasks: 7
    cpus_per_task: 28
    partition: nomaster

cluster_category_refinement:
    nodes: 7
    ntasks: 196
    ntasks_per_node: 28
    partition: nomaster

cluster_category_database:
    nodes: 7
    ntasks: 196
    ntasks_per_node: 28
    partition: nomaster

cluster_category_stats:
    time: 1000:00:00
    nodes: 7
    ntasks_per_node: 1
    ntasks: 7
    cpus_per_task: 28
    partition: nomaster

cluster_communities_dbs:
    time: 1000:00:00
    nodes: 7
    ntasks: 196
    ntasks_per_node: 28
    partition: nomaster

cluster_communities_inference:
    time: 1000:00:00
    nodes: 7
    ntasks_per_node: 4
    ntasks: 28
    partition: nomaster
